# shellcheck shell=sh

CC_PLUGIN_DEFAULT="bt-wifi"
CC_WIRELESS_SSID_DEFAULT="BTWi-fi\|BTWifi-with-FON"
CC_WIRELESS_IFACE_DEFAULT="wlan-sta" # apcli0 | wlan-sta
CC_FAILURE_LIMIT_BEFORE_REBOOTING_DEFAULT="5"

# Allow overriding of defaults
CC_PLUGIN=${CC_PLUGIN:-${CC_PLUGIN_DEFAULT}}
CC_WIRELESS_SSID=${CC_WIRELESS_SSID:-${CC_WIRELESS_SSID_DEFAULT}}
CC_WIRELESS_IFACE=${CC_WIRELESS_IFACE:-${CC_WIRELESS_IFACE_DEFAULT}}
CC_FAILURE_LIMIT_BEFORE_REBOOTING=${CC_FAILURE_LIMIT_BEFORE_REBOOTING:-${CC_FAILURE_LIMIT_BEFORE_REBOOTING_DEFAULT}}

# Try and autodetect iface if nothing specified
CC_WIRELESS_IFACE_AUTO=$(uci get wireless.sta.ifname 2> /dev/null)
CC_WIRELESS_IFACE=${CC_WIRELESS_IFACE:-$CC_WIRELESS_IFACE_AUTO}

export CC_PLUGIN
export CC_WIRELESS_SSID
export CC_WIRELESS_IFACE
export CC_FAILURE_LIMIT_BEFORE_REBOOTING
