# shellcheck shell=sh

CC_PLUGIN="bt-wifi"

CC_WIRELESS_SSID="BTWi-fi\|BTWifi-with-FON"
CC_WIRELESS_IFACE="" # apcli0 | wlan-sta
CC_FAILURE_LIMIT_BEFORE_REBOOTING=5

STATEBOT_LOG_LEVEL=4
STATEBOT_USE_LOGGER=0

CC_WIRELESS_IFACE_AUTO=$(uci get wireless.sta.ifname 2> /dev/null)
CC_WIRELESS_IFACE=${CC_WIRELESS_IFACE:-$CC_WIRELESS_IFACE_AUTO}

export CC_PLUGIN
export CC_WIRELESS_SSID
export CC_WIRELESS_IFACE
export CC_FAILURE_LIMIT_BEFORE_REBOOTING
export STATEBOT_LOG_LEVEL
export STATEBOT_USE_LOGGER
